<a href="https://colab.research.google.com/github/ToniRV/MIT_6.862_Applied_Machine_Learning/blob/master/MIT_6_036_HW06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIT 6.036 Spring 2020: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.

In [0]:
import numpy as np

# **Problem 2**

You may find it helpful to implement a softmax function to use for solving the problems.

In [0]:
# Implement Softmax
def SM(z):
    '''
    z is a column vector
    '''
    total = np.sum(np.exp(z))
    return np.exp(z) / total

In [7]:
z = np.array([[1], [0], [-1]])
SM(z)

array([[0.66524096],
       [0.24472847],
       [0.09003057]])

**Problem 2.A**

In [15]:
z = np.array([[-1, 0, 1]]).T
# Your code here
SM(z)

array([[0.09003057],
       [0.24472847],
       [0.66524096]])

**Problem 2.C - 2.F**

In [24]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T
# Your code here
# Gradient of NLL wrt W:
grad = np.dot(x, (SM(np.dot(w.T, x))-y).T)
print(grad)

# One-step opt with step=0.5
w = w - 0.5 * grad
print(w.tolist())

# New probabilities given new w
p = SM(np.dot(w.T, x))
p

[[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]
[[0.8776357644726012, -0.8326204778874109, -2.04501528658519], [-1.1223642355273988, 2.167379522112589, 0.9549847134148097]]


array([[0.15918761],
       [0.77245284],
       [0.06835955]])

# **Problem 3**

**Problem 3.1**

You may choose to draft your implementation here. We recommend looking at the ReLU plot at the top of the homework page for better understanding.

In [0]:
def dReLU_dz(z):
    '''
    z is a column vector
    You should return a column vector
    '''
    return (z > 0).astype(int)